[phases]

[phases.setup]
nixpkgs = ["python311", "pip", "build-essential"]
run = """
pip install --upgrade pip
pip install -r requirements.txt
"""

[phases.build]
run = """
python manage.py collectstatic --noinput
"""

[phases.start]
cmd = "uvicorn PixelDomination.asgi:application --host 0.0.0.0 --port ${PORT}"
